-- MySQL Script generated by MySQL Workbench
-- Sun Mar  4 21:25:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema APIdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema APIdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `APIdb` DEFAULT CHARACTER SET utf8 ;
USE `APIdb` ;

-- -----------------------------------------------------
-- Table `APIdb`.`tb_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `APIdb`.`tb_usuario` ;

CREATE TABLE IF NOT EXISTS `APIdb`.`tb_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `APIdb`.`tb_ordem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `APIdb`.`tb_ordem` ;

CREATE TABLE IF NOT EXISTS `APIdb`.`tb_ordem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarioid` INT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `qtdbtc` FLOAT NOT NULL,
  `valorporbtc` FLOAT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_ordem_tb_usuario_idx` (`usuarioid` ASC),
  CONSTRAINT `fk_tb_ordem_tb_usuario`
    FOREIGN KEY (`usuarioid`)
    REFERENCES `APIdb`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `APIdb`.`tb_cotacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `APIdb`.`tb_cotacao` ;

CREATE TABLE IF NOT EXISTS `APIdb`.`tb_cotacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `moeda` VARCHAR(10) NOT NULL,
  `valor` FLOAT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `exchange` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
